apiVersion: v1
kind: Service
metadata:
  labels:
    app: Supplierssrv
    service: Supplierssrv
  name: Supplierssrv
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: Suppliers