apiVersion: apps/v1
kind: Deployment
metadata:
  name: DemandFlow-Service
  labels:
    app: DemandFlow-Service
spec:
  selector:
    matchLabels:
      app: DemandFlow-Service
  replicas:  1
  template:
    metadata:
      labels:
        app: DemandFlow-Service
    spec:
      containers:
       - name: DemandFlow-Service
         image: evolza/DemandFlow-Service:latest
         imagePullPolicy: Always
         ports:
          - containerPort: 8080
            name: rest
      imagePullSecrets:
          - name: notavailable